spring.application.name=employeemanagementsystem

# Database details - External MySQL (Render \u0935\u0930 localhost \u0915\u093E\u092E \u0915\u0930\u0923\u093E\u0930 \u0928\u093E\u0939\u0940)
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/jpaexample}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.properties.dialect=org.hibernate.dialect.MySQLDialect

# Server Port (Render \u0938\u093E\u0920\u0940)
server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sumitnahire72@gmail.com
spring.mail.password=${MAIL_PASSWORD:qbfc lmvo redi zibm}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true